"""Leakage-safe renovation-episode probabilities and valuation challengers.

A flip is a sequence, not a property characteristic: acquisition, permits,
completion, and resale.  This module reconstructs that sequence from exact
event dates, learns the probability of a large time-adjusted recovery on
historical repeat sales, and tests whether the probability improves valuation
or prediction-risk information on an untouched future slice.

The auxiliary target may use the resale price, but that price never enters an
input feature.  Fit-row probabilities are generated by expanding-time
cross-fitting; validation and test probabilities come from labels completed in
the fit period only.  Later permits never appear in an earlier row.
"""

from __future__ import annotations

import json
import logging
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Final

import lightgbm as lgb
import numpy as np
import polars as pl

from philly_fair_measure import config
from philly_fair_measure.features.renovation_episodes import (
    EPISODE_RAW_FEATURES,
    add_renovation_episode_features,
)
from philly_fair_measure.ingest.derived import write_derived_table
from philly_fair_measure.ingest.manifests import InputRef, read_derived_manifest
from philly_fair_measure.models.baseline import (
    DEFAULT_CATBOOST_PARAMS,
    DEFAULT_LGB_PARAMS,
    RECENCY_HALF_LIFE_YEARS,
    _encode,
    _fit_category_mappings,
    _load_frame,
    catboost_frame,
    feature_lists,
)
from philly_fair_measure.models.metrics import (
    evaluate_estimates,
    stack_weight,
    vertical_equity_indicator,
)
from philly_fair_measure.models.renovation_state import (
    cross_fitted_transition_probability,
)
from philly_fair_measure.models.renovation_state import (
    fit_calibrated_transition_model as _fit_calibrated_classifier,
)
from philly_fair_measure.models.renovation_state import (
    predict_transition_probability as _predict_probability,
)

from .q1_experiments import _calibrate, _fit_value_model

logger = logging.getLogger(__name__)

MIN_DISTRICT_ROWS: Final = 150

PERMIT_SEQUENCE_INPUTS: Final = tuple(
    name for name in EPISODE_RAW_FEATURES if name != "episode_prior_discount_log"
)
MARKET_CONTEXT_INPUTS: Final = (
    "episode_eligible",
    "episode_days_since_acquisition",
    "episode_prior_discount_log",
    "mkt_parcel_prev_log_price_ref",
    "mkt_knn_price_anchor_log",
    "mkt_knn_n",
    "state_distress_evidence",
    "state_measurement_conflict_evidence",
    "quality_characteristic_conflict_score",
)


@dataclass(frozen=True)
class RenovationDecision:
    challenger: str
    promote_to_full_retrain: bool
    hard_gates_passed: bool
    material_benefit: bool
    failed_gates: tuple[str, ...]


@dataclass(frozen=True)
class RenovationEpisodeResult:
    metrics: pl.DataFrame
    decisions: tuple[RenovationDecision, ...]
    diagnostics: dict[str, object]
    metrics_path: Path
    decisions_path: Path


def _classification_diagnostics(frame: pl.DataFrame, probability: np.ndarray) -> dict[str, object]:
    from sklearn.metrics import brier_score_loss, roc_auc_score

    mask = frame["episode_high_recovery_label"].is_not_null().to_numpy()
    if int(mask.sum()) < 20:
        return {"rows": int(mask.sum()), "status": "insufficient_support"}
    target = frame.filter(pl.Series(mask))["episode_high_recovery_label"].to_numpy()
    score = probability[mask]
    prior = float(target.mean())
    edges = np.unique(np.quantile(score, np.linspace(0.0, 1.0, 6)))
    calibration_rows: list[dict[str, object]] = []
    if len(edges) > 1:
        bucket = np.digitize(score, edges[1:-1])
        for value in range(len(edges) - 1):
            selected = bucket == value
            if not np.any(selected):
                continue
            calibration_rows.append(
                {
                    "bucket": value + 1,
                    "n": int(selected.sum()),
                    "mean_probability": float(score[selected].mean()),
                    "observed_rate": float(target[selected].mean()),
                }
            )
    return {
        "rows": int(mask.sum()),
        "positive_rate": prior,
        "roc_auc": float(roc_auc_score(target, score)),
        "brier": float(brier_score_loss(target, score)),
        "constant_prior_brier": float(brier_score_loss(target, np.full(len(target), prior))),
        "calibration": calibration_rows,
    }


def _probability_ablation_diagnostics(
    fit: pl.DataFrame, val: pl.DataFrame, test: pl.DataFrame, *, seed: int
) -> dict[str, object]:
    labeled = fit.filter(pl.col("episode_high_recovery_label").is_not_null())
    results: dict[str, object] = {}
    feature_sets = {
        "permit_sequence_only": PERMIT_SEQUENCE_INPUTS,
        "market_context_only": MARKET_CONTEXT_INPUTS,
    }
    for offset, (name, inputs) in enumerate(feature_sets.items()):
        classifier = _fit_calibrated_classifier(labeled, inputs=inputs, seed=seed + offset)
        if classifier is None:
            results[name] = {"status": "insufficient_support"}
            continue
        results[name] = {
            "inputs": list(inputs),
            "validation": _classification_diagnostics(val, _predict_probability(classifier, val)),
            "test": _classification_diagnostics(test, _predict_probability(classifier, test)),
        }
    return results


def _segments(test: pl.DataFrame, probability: np.ndarray) -> list[tuple[str, str, np.ndarray]]:
    actual = test["sale_price"].to_numpy()
    financed = (test["fin_cash_sale"].fill_null(1.0) == 0.0).to_numpy()
    financed_edges = np.quantile(actual[financed], [0.2, 0.4, 0.6, 0.8])
    financed_q = np.digitize(actual, financed_edges) + 1
    segments: list[tuple[str, str, np.ndarray]] = [
        ("overall", "all", np.ones(test.height, dtype=bool)),
        ("finance", "financed", financed),
        ("finance", "cash", ~financed),
        ("financed_price", "q1", financed & (financed_q == 1)),
        ("financed_price", "q5", financed & (financed_q == 5)),
        (
            "episode",
            "eligible_repeat",
            (test["episode_eligible"].cast(pl.Float64).fill_null(0.0) > 0).to_numpy(),
        ),
        (
            "episode",
            "permit_bundle",
            (test["episode_permit_bundle"].cast(pl.Float64).fill_null(0.0) > 0).to_numpy(),
        ),
        (
            "episode",
            "confirmed_transition",
            (test["episode_permit_confirmed_label"].cast(pl.Float64).fill_null(0.0) > 0).to_numpy(),
        ),
        ("episode", "high_probability", probability >= 0.75),
    ]
    for label, column in {
        "characteristic_outlier": "quality_characteristic_outlier",
        "active_work": "state_active_work_evidence",
        "distress": "state_distress_evidence",
    }.items():
        if column not in test.columns:
            continue
        if test.schema[column] == pl.Boolean:
            mask = test[column].fill_null(False).to_numpy()
        else:
            mask = (test[column].cast(pl.Float64).fill_null(0.0) > 0.5).to_numpy()
        segments.append(("risk", label, mask))
    district = test["loc_district"].cast(pl.String).fill_null("unknown")
    for label in district.unique().sort().to_list():
        mask = (district == label).to_numpy()
        if int(mask.sum()) >= MIN_DISTRICT_ROWS:
            segments.append(("district", str(label), mask))
    return segments


def _evaluate(
    predictions: dict[str, np.ndarray],
    test: pl.DataFrame,
    probability: np.ndarray,
    iterations: dict[str, int],
) -> pl.DataFrame:
    actual = test["sale_price"].to_numpy()
    time_adj = test["time_adj_log"].cast(pl.Float64).fill_null(0.0).to_numpy()
    rows: list[dict[str, object]] = []
    for challenger, prediction_log in predictions.items():
        estimate = np.exp(prediction_log - time_adj)
        for segment_type, segment, mask in _segments(test, probability):
            if int(mask.sum()) < 3:
                continue
            metrics = evaluate_estimates(estimate[mask], actual[mask])
            vei = vertical_equity_indicator(estimate[mask], actual[mask])
            rows.append(
                {
                    "challenger": challenger,
                    "segment_type": segment_type,
                    "segment": segment,
                    "best_iteration": iterations[challenger],
                    **metrics.as_row(),
                    "vei": vei.vei,
                }
            )
    table = pl.DataFrame(rows)
    incumbent = table.filter(pl.col("challenger") == "incumbent").select(
        "segment_type",
        "segment",
        pl.col("rmse_log").alias("base_rmse_log"),
        pl.col("cod").alias("base_cod"),
        pl.col("prb").alias("base_prb"),
        pl.col("vei").alias("base_vei"),
    )
    return table.join(incumbent, on=["segment_type", "segment"], how="left").with_columns(
        (pl.col("rmse_log") - pl.col("base_rmse_log")).alias("delta_rmse_log"),
        (pl.col("cod") - pl.col("base_cod")).alias("delta_cod"),
        (pl.col("prb").abs() - pl.col("base_prb").abs()).alias("delta_abs_prb"),
        (pl.col("vei").abs() - pl.col("base_vei").abs()).alias("delta_abs_vei"),
    )


def _fit_stack_candidate(
    fit: pl.DataFrame,
    val: pl.DataFrame,
    test: pl.DataFrame,
    numeric: list[str],
    categorical: list[str],
    *,
    seed: int,
) -> tuple[np.ndarray, dict[str, float | int]]:
    from catboost import CatBoostRegressor, Pool

    numeric = list(dict.fromkeys(numeric))
    mappings = _fit_category_mappings(fit, categorical)
    x_fit = _encode(fit, mappings, numeric, categorical)
    x_val = _encode(val, mappings, numeric, categorical)
    x_test = _encode(test, mappings, numeric, categorical)
    y_fit = np.asarray(
        np.log(fit["sale_price"].to_numpy())
        + fit["time_adj_log"].cast(pl.Float64).fill_null(0.0).to_numpy(),
        dtype=np.float64,
    )
    y_val = np.asarray(
        np.log(val["sale_price"].to_numpy())
        + val["time_adj_log"].cast(pl.Float64).fill_null(0.0).to_numpy(),
        dtype=np.float64,
    )
    age_days = fit.select(
        (pl.col("sale_date").max() - pl.col("sale_date")).dt.total_days().alias("age")
    )["age"].to_numpy()
    recency_weight = np.power(0.5, age_days / (RECENCY_HALF_LIFE_YEARS * 365.25))
    train = lgb.Dataset(
        x_fit,
        label=y_fit,
        weight=recency_weight,
        feature_name=numeric + categorical,
        categorical_feature=categorical,
    )
    lightgbm = lgb.train(
        {**DEFAULT_LGB_PARAMS, "seed": seed},
        train,
        num_boost_round=5_000,
        valid_sets=[train.create_valid(x_val, label=y_val)],
        callbacks=[lgb.early_stopping(100, verbose=False)],
    )
    cat_index = list(range(len(numeric), len(numeric) + len(categorical)))
    catboost = CatBoostRegressor(
        **{**DEFAULT_CATBOOST_PARAMS, "random_seed": seed},
        verbose=False,
        allow_writing_files=False,
    )
    catboost.fit(
        Pool(
            catboost_frame(fit, numeric, categorical),
            label=y_fit,
            weight=recency_weight,
            cat_features=cat_index,
        ),
        eval_set=Pool(
            catboost_frame(val, numeric, categorical),
            label=y_val,
            cat_features=cat_index,
        ),
        use_best_model=True,
    )
    lgb_val = np.asarray(
        lightgbm.predict(x_val, num_iteration=lightgbm.best_iteration), dtype=np.float64
    )
    lgb_test = np.asarray(
        lightgbm.predict(x_test, num_iteration=lightgbm.best_iteration), dtype=np.float64
    )
    cat_val = np.asarray(
        catboost.predict(catboost_frame(val, numeric, categorical)), dtype=np.float64
    )
    cat_test = np.asarray(
        catboost.predict(catboost_frame(test, numeric, categorical)), dtype=np.float64
    )
    weight_lightgbm = stack_weight(lgb_val, cat_val, y_val)
    stack_val = weight_lightgbm * lgb_val + (1.0 - weight_lightgbm) * cat_val
    stack_test = weight_lightgbm * lgb_test + (1.0 - weight_lightgbm) * cat_test
    _, calibrated_test = _calibrate(stack_val, stack_test, val)
    return calibrated_test, {
        "lightgbm_best_iteration": int(lightgbm.best_iteration),
        "catboost_best_iteration": int(catboost.get_best_iteration()),
        "weight_lightgbm": weight_lightgbm,
    }


def _metric(
    table: pl.DataFrame, challenger: str, segment_type: str, segment: str, name: str
) -> float:
    value = table.filter(
        (pl.col("challenger") == challenger)
        & (pl.col("segment_type") == segment_type)
        & (pl.col("segment") == segment)
    )[name]
    return float(value[0]) if len(value) and value[0] is not None else float("nan")


def _decide(table: pl.DataFrame, challengers: list[str]) -> tuple[RenovationDecision, ...]:
    decisions: list[RenovationDecision] = []
    for challenger in challengers:
        checks = {
            "overall_rmse": _metric(table, challenger, "overall", "all", "delta_rmse_log") <= 0.002,
            "financed_rmse": _metric(table, challenger, "finance", "financed", "delta_rmse_log")
            <= 0.002,
            "financed_q1_rmse": _metric(table, challenger, "financed_price", "q1", "delta_rmse_log")
            <= 0.005,
            "financed_q5_rmse": _metric(table, challenger, "financed_price", "q5", "delta_rmse_log")
            <= 0.003,
            "overall_abs_prb": _metric(table, challenger, "overall", "all", "delta_abs_prb")
            <= 0.005,
            "overall_abs_vei": _metric(table, challenger, "overall", "all", "delta_abs_vei") <= 1.0,
        }
        for cohort in ("characteristic_outlier", "active_work", "distress"):
            delta = _metric(table, challenger, "risk", cohort, "delta_rmse_log")
            checks[f"{cohort}_rmse"] = np.isfinite(delta) and delta <= 0.003
        district = table.filter(
            (pl.col("challenger") == challenger) & (pl.col("segment_type") == "district")
        )
        worst_district = district["delta_rmse_log"].max() if district.height else None
        checks["worst_district_rmse"] = bool(
            worst_district is None
            or (isinstance(worst_district, int | float) and worst_district <= 0.01)
        )
        failed = tuple(name for name, passed in checks.items() if not passed)
        # The experiment exists to identify renovation/state transitions, not
        # to exploit a generic repeat-sale or transaction-channel shortcut.
        # Overall gains count only after an intended segment also improves.
        improvements = [
            -_metric(table, challenger, "financed_price", "q1", "delta_rmse_log") >= 0.002,
            -_metric(table, challenger, "episode", "confirmed_transition", "delta_rmse_log")
            >= 0.003,
            -_metric(table, challenger, "episode", "permit_bundle", "delta_rmse_log") >= 0.003,
        ]
        material = any(improvements)
        decisions.append(
            RenovationDecision(
                challenger=challenger,
                promote_to_full_retrain=not failed and material,
                hard_gates_passed=not failed,
                material_benefit=material,
                failed_gates=failed,
            )
        )
    return tuple(decisions)


def _error_probability_diagnostics(
    test: pl.DataFrame, incumbent_log: np.ndarray, probability: np.ndarray
) -> dict[str, object]:
    actual_log = (
        np.log(test["sale_price"].to_numpy())
        + test["time_adj_log"].cast(pl.Float64).fill_null(0.0).to_numpy()
    )
    absolute_error = np.abs(actual_log - incumbent_log)
    eligible = (test["episode_eligible"].cast(pl.Float64).fill_null(0.0) > 0).to_numpy()
    if int(eligible.sum()) < 20:
        return {"rows": int(eligible.sum()), "status": "insufficient_support"}
    table = pl.DataFrame(
        {"probability": probability[eligible], "absolute_error": absolute_error[eligible]}
    )
    correlation = table.select(pl.corr("probability", "absolute_error", method="spearman")).item()
    return {
        "rows": int(eligible.sum()),
        "spearman_probability_abs_error": float(correlation) if correlation is not None else None,
        "low_probability_rmse": float(
            np.sqrt(np.mean(np.square(absolute_error[eligible][probability[eligible] < 0.25])))
        )
        if np.any(probability[eligible] < 0.25)
        else None,
        "high_probability_rmse": float(
            np.sqrt(np.mean(np.square(absolute_error[eligible][probability[eligible] >= 0.75])))
        )
        if np.any(probability[eligible] >= 0.75)
        else None,
    }


def _risk_challenger_diagnostics(
    root: Path,
    probability_frame: pl.DataFrame,
    *,
    seed: int,
) -> dict[str, object]:
    """Test episode probability as risk evidence against the shipped stack."""
    from scipy.stats import spearmanr

    from philly_fair_measure.models.conformal import split_frames
    from philly_fair_measure.models.risk import (
        RISK_FEATURE_NAMES,
        _point_log,
        _reference_log_price,
        _risk_evaluation,
        _risk_matrix,
    )
    from philly_fair_measure.models.scoring import latest_run_dir

    try:
        run_dir = latest_run_dir("baseline", root)
        _, val, test = split_frames(run_dir, root)
    except (FileNotFoundError, ValueError) as exc:
        return {"status": "unavailable", "reason": str(exc)}

    lookup = probability_frame.select(
        "sale_id", "parcel_id", "sale_date", "episode_transition_probability"
    ).unique(subset=["sale_id", "parcel_id", "sale_date"], keep="last")
    val = val.join(lookup, on=["sale_id", "parcel_id", "sale_date"], how="left").with_columns(
        pl.col("episode_transition_probability").fill_null(0.0)
    )
    test = test.join(lookup, on=["sale_id", "parcel_id", "sale_date"], how="left").with_columns(
        pl.col("episode_transition_probability").fill_null(0.0)
    )
    cut = max(1, int(val.height * 0.8))
    risk_fit, risk_cal = val.head(cut), val.tail(val.height - cut)
    base_fit, base_cal, base_test = (
        _risk_matrix(run_dir, frame) for frame in (risk_fit, risk_cal, test)
    )
    p_fit = risk_fit["episode_transition_probability"].to_numpy()
    p_cal = risk_cal["episode_transition_probability"].to_numpy()
    p_test = test["episode_transition_probability"].to_numpy()
    y_fit = np.abs(_reference_log_price(run_dir, risk_fit) - _point_log(run_dir, risk_fit))
    y_cal = np.abs(_reference_log_price(run_dir, risk_cal) - _point_log(run_dir, risk_cal))
    actual_test = _reference_log_price(run_dir, test)
    point_test = _point_log(run_dir, test)
    test_error = np.abs(actual_test - point_test)

    candidates = {
        "incumbent_risk": (base_fit, base_cal, base_test, list(RISK_FEATURE_NAMES)),
        "episode_probability_risk": (
            np.column_stack([base_fit, p_fit]),
            np.column_stack([base_cal, p_cal]),
            np.column_stack([base_test, p_test]),
            [*RISK_FEATURE_NAMES, "episode_transition_probability"],
        ),
    }
    results: dict[str, object] = {"run_id": run_dir.name}
    for name, (x_fit, x_cal, x_test, feature_names) in candidates.items():
        model = lgb.train(
            {
                "objective": "regression_l1",
                "metric": "l1",
                "learning_rate": 0.03,
                "num_leaves": 31,
                "min_data_in_leaf": 100,
                "feature_fraction": 0.9,
                "lambda_l2": 2.0,
                "verbose": -1,
                "seed": seed,
            },
            lgb.Dataset(x_fit, label=y_fit, feature_name=feature_names),
            num_boost_round=1_000,
            valid_sets=[lgb.Dataset(x_cal, label=y_cal)],
            callbacks=[lgb.early_stopping(75, verbose=False)],
        )
        cal_score = np.maximum(np.asarray(model.predict(x_cal)), 0.0)
        elevated, high = (float(value) for value in np.quantile(cal_score, [0.75, 0.90]))
        test_score = np.maximum(np.asarray(model.predict(x_test)), 0.0)
        evaluation = _risk_evaluation(test_score, actual_test, point_test, elevated, high)
        eligible = p_test > 0
        eligible_correlation = (
            float(spearmanr(test_score[eligible], test_error[eligible]).statistic)
            if int(eligible.sum()) >= 20
            else None
        )
        results[name] = {
            "best_iteration": int(model.best_iteration),
            "test_spearman": float(spearmanr(test_score, test_error).statistic),
            "eligible_episode_rows": int(eligible.sum()),
            "eligible_episode_spearman": eligible_correlation,
            "evaluation": evaluation.to_dicts(),
        }
    return results


def renovation_episode_check(
    data_dir: Path | None = None, *, full_stack: bool = False, seed: int = 42
) -> RenovationEpisodeResult:
    root = data_dir if data_dir is not None else config.data_dir()
    mart_path = root / "marts" / "sale_features.parquet"
    permits_path = root / "staged" / "permits.parquet"
    frame = add_renovation_episode_features(_load_frame(mart_path), pl.read_parquet(permits_path))
    n_test = max(1, int(frame.height * 0.1))
    train, test = frame.head(frame.height - n_test), frame.tail(n_test)
    n_val = max(1, int(train.height * 0.1))
    fit, val = train.head(train.height - n_val), train.tail(n_val)

    probability_result = cross_fitted_transition_probability(fit, val, test, seed=seed)
    probabilities = probability_result.probabilities
    probability_diagnostics = probability_result.diagnostics
    fit = fit.with_columns(pl.Series("episode_transition_probability", probabilities["fit"]))
    val = val.with_columns(pl.Series("episode_transition_probability", probabilities["val"]))
    test = test.with_columns(pl.Series("episode_transition_probability", probabilities["test"]))

    base_numeric, categorical = feature_lists(time_adjusted=True)
    candidates = {
        "incumbent": base_numeric,
        "episode_raw": [*base_numeric, *EPISODE_RAW_FEATURES],
        "episode_probability": [*base_numeric, "episode_transition_probability"],
        "episode_combined": [
            *base_numeric,
            *EPISODE_RAW_FEATURES,
            "episode_transition_probability",
        ],
    }
    predictions: dict[str, np.ndarray] = {}
    iterations: dict[str, int] = {}
    for name, numeric in candidates.items():
        fitted = _fit_value_model(
            fit,
            val,
            {"val": val, "test": test},
            list(dict.fromkeys(numeric)),
            categorical,
            seed=seed,
        )
        _, predictions[name] = _calibrate(
            fitted.predictions["val"], fitted.predictions["test"], val
        )
        iterations[name] = fitted.best_iteration
        logger.info("renovation challenger %s fit at iteration %d", name, fitted.best_iteration)

    metrics = _evaluate(predictions, test, probabilities["test"], iterations)
    challenger_names = [name for name in candidates if name != "incumbent"]
    decisions = _decide(metrics, challenger_names)
    stack_diagnostics: dict[str, object] = {"status": "not_requested"}
    if full_stack:
        stack_predictions: dict[str, np.ndarray] = {}
        stack_iterations: dict[str, int] = {}
        stack_fit_details: dict[str, object] = {}
        for name, numeric in {
            "incumbent": base_numeric,
            "episode_combined": candidates["episode_combined"],
        }.items():
            prediction, details = _fit_stack_candidate(
                fit, val, test, numeric, categorical, seed=seed
            )
            stack_predictions[name] = prediction
            stack_iterations[name] = int(details["lightgbm_best_iteration"])
            stack_fit_details[name] = details
            logger.info("full-stack renovation challenger %s complete", name)
        stack_metrics = _evaluate(stack_predictions, test, probabilities["test"], stack_iterations)
        stack_decisions = _decide(stack_metrics, ["episode_combined"])
        mart_manifest = read_derived_manifest(mart_path)
        permit_manifest = read_derived_manifest(permits_path)
        stack_metrics_path, _ = write_derived_table(
            stack_metrics,
            root,
            "diagnostics",
            "renovation_episode_stack_metrics",
            [
                InputRef(
                    dataset=f"{mart_manifest.layer}/{mart_manifest.table}",
                    fetched_at=mart_manifest.built_at.isoformat(),
                ),
                InputRef(
                    dataset=f"{permit_manifest.layer}/{permit_manifest.table}",
                    fetched_at=permit_manifest.built_at.isoformat(),
                ),
            ],
            notes="full LightGBM/CatBoost stack gate for renovation episode probability",
        )
        stack_decisions_path = stack_metrics_path.with_name(
            "renovation_episode_stack_metrics.decisions.json"
        )
        stack_decisions_path.write_text(
            json.dumps(
                {
                    "built_at": datetime.now(UTC).isoformat(),
                    "fit": stack_fit_details,
                    "decisions": [asdict(item) for item in stack_decisions],
                },
                indent=2,
            )
            + "\n"
        )
        stack_diagnostics = {
            "status": "complete",
            "fit": stack_fit_details,
            "decisions": [asdict(item) for item in stack_decisions],
            "metrics_path": str(stack_metrics_path),
            "decisions_path": str(stack_decisions_path),
        }
    diagnostics: dict[str, object] = {
        **probability_diagnostics,
        "rows": {"fit": fit.height, "validation": val.height, "test": test.height},
        "validation_probability": _classification_diagnostics(val, probabilities["val"]),
        "test_probability": _classification_diagnostics(test, probabilities["test"]),
        "probability_ablations": _probability_ablation_diagnostics(fit, val, test, seed=seed + 100),
        "risk_challenger": _risk_challenger_diagnostics(
            root,
            pl.concat(
                [
                    fit.select(
                        "sale_id", "parcel_id", "sale_date", "episode_transition_probability"
                    ),
                    val.select(
                        "sale_id", "parcel_id", "sale_date", "episode_transition_probability"
                    ),
                    test.select(
                        "sale_id", "parcel_id", "sale_date", "episode_transition_probability"
                    ),
                ]
            ),
            seed=seed,
        ),
        "test_error_stratification": _error_probability_diagnostics(
            test, predictions["incumbent"], probabilities["test"]
        ),
        "test_episode_rows": int(test["episode_eligible"].sum()),
        "test_permit_bundle_rows": int(test["episode_permit_bundle"].sum()),
        "test_confirmed_transition_rows": int(test["episode_permit_confirmed_label"].sum()),
        "full_stack": stack_diagnostics,
    }

    mart_manifest = read_derived_manifest(mart_path)
    permit_manifest = read_derived_manifest(permits_path)
    metrics_path, _ = write_derived_table(
        metrics,
        root,
        "diagnostics",
        "renovation_episode_metrics",
        [
            InputRef(
                dataset=f"{mart_manifest.layer}/{mart_manifest.table}",
                fetched_at=mart_manifest.built_at.isoformat(),
            ),
            InputRef(
                dataset=f"{permit_manifest.layer}/{permit_manifest.table}",
                fetched_at=permit_manifest.built_at.isoformat(),
            ),
        ],
        notes="exact-date sale-permit-resale episodes; expanding-time probability gate",
    )
    decisions_path = metrics_path.with_name("renovation_episode_metrics.decisions.json")
    decisions_path.write_text(
        json.dumps(
            {
                "built_at": datetime.now(UTC).isoformat(),
                "diagnostics": diagnostics,
                "decisions": [asdict(item) for item in decisions],
            },
            indent=2,
        )
        + "\n"
    )
    return RenovationEpisodeResult(
        metrics=metrics,
        decisions=decisions,
        diagnostics=diagnostics,
        metrics_path=metrics_path,
        decisions_path=decisions_path,
    )
