/**
 * Drift guard for the frontend — the sync-docs equivalent the .vue files never had.
 *
 * siteStats.json is regenerated by `fair-measure export-web-stats` on every retrain,
 * and the pages import it, so bound values (`{{ ... }}`) are always fresh. The failure
 * mode this test prevents is a run-dependent number or date typed *as a literal* into
 * rendered prose (or a comment): it looks right the day it lands, then silently rots on
 * the next retrain. We shipped exactly that — a frozen "Data updated 2026-07-04" and a
 * caption that hand-repeated "PRB -0.06 / COD 25.9" after both had moved.
 *
 * Three classes are caught here:
 *   1. A current siteStats metric value (median ratio / COD / PRD / PRB) appearing as a
 *      literal in template prose — caught at introduction, when the literal still matches
 *      the fresh JSON. The fix is always to bind it: {{ fmt(full.model.prb, 2) }}.
 *   2. An ISO date literal (2026-07-04) anywhere in .vue/.css — provenance is never
 *      written this way except when frozen; real UI dates read from stats.meta.generated_at.
 *   3. A pinned run-id (20260707T030251Z) — those come from stats.meta.model_run_id.
 *
 * When this fails it means: don't hardcode the number, read it from siteStats.
 */
import { readFileSync, readdirSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import stats from '@/data/siteStats.json'

const SRC = join(dirname(fileURLToPath(import.meta.url)), '..')

/** IAAO band / definition constants that legitimately appear as prose numbers and must
 * never be treated as stats even if a run's metric happens to round to one of them. */
const CONSTANTS = new Set(['0.90', '1.10', '0.98', '1.03', '1.00', '0.05'])

type Card = { median_ratio: number; cod: number; prd: number; prb: number }

function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const p = join(dir, e.name)
    return e.isDirectory() ? walk(p) : [p]
  })
}

const allFiles = walk(SRC)
const vueFiles = allFiles.filter((f) => f.endsWith('.vue'))
const styleFiles = allFiles.filter((f) => f.endsWith('.css'))
const rel = (f: string) => relative(SRC, f)
const read = (f: string) => readFileSync(f, 'utf8')

/** Visible text nodes of a single-file component: the template with mustache bindings,
 * tags (and thus all attributes: class, :style, SVG coords, aria-labels) removed. */
function visibleProse(src: string): string {
  const tpl = src.match(/<template>([\s\S]*)<\/template>/)?.[1] ?? ''
  return tpl
    .replace(/\{\{[\s\S]*?\}\}/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&[a-z]+;/gi, ' ')
}

const escape = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

/** The run-dependent metric literals, at the precision the site prints each one, with both
 * hyphen glyphs the app uses (ASCII in fmt(), U+2212 in the money formatters). */
function sensitiveLiterals(): Map<string, string> {
  const out = new Map<string, string>()
  const add = (value: number, dp: number, source: string) => {
    const s = value.toFixed(dp)
    const variants = s.startsWith('-') ? [s, `−${s.slice(1)}`] : [s]
    for (const lit of variants) {
      if (CONSTANTS.has(lit.replace('−', '-'))) continue
      if (!out.has(lit)) out.set(lit, source)
    }
  }
  const cards: Record<string, { model: Card; opa: Card }> = {
    full_card: stats.full_card,
    iaao_card: stats.iaao_card,
    condo_card: stats.condo_card,
  }
  for (const [card, sides] of Object.entries(cards)) {
    for (const side of ['model', 'opa'] as const) {
      const c = sides[side]
      add(c.median_ratio, 3, `${card}.${side}.median_ratio`)
      add(c.cod, 1, `${card}.${side}.cod`)
      add(c.prd, 3, `${card}.${side}.prd`)
      add(c.prb, 2, `${card}.${side}.prb`)
      add(c.prb, 3, `${card}.${side}.prb`)
    }
  }
  return out
}

describe('frontend does not hardcode run-dependent stats', () => {
  it('no siteStats metric value is typed as a literal in rendered prose', () => {
    const literals = sensitiveLiterals()
    const offenders: string[] = []
    for (const file of vueFiles) {
      const prose = visibleProse(read(file))
      for (const [lit, source] of literals) {
        // require numeric-literal boundaries so "24.9" does not match inside "124.95"
        if (new RegExp(`(?<![\\d.])${escape(lit)}(?![\\d])`).test(prose)) {
          offenders.push(`${rel(file)}: "${lit}" == siteStats.${source} — bind it, don't hardcode`)
        }
      }
    }
    expect(offenders, `\n${offenders.join('\n')}\n`).toEqual([])
  })

  it('no frozen ISO date or run-id literal in .vue/.css (read them from stats.meta)', () => {
    const offenders: string[] = []
    for (const file of [...vueFiles, ...styleFiles]) {
      const text = read(file)
      for (const m of text.matchAll(/\b20\d\d-\d\d-\d\d\b/g)) {
        offenders.push(`${rel(file)}: frozen date "${m[0]}" — use stats.meta.generated_at`)
      }
      for (const m of text.matchAll(/\b20\d{6}T\d{6}Z\b/g)) {
        offenders.push(`${rel(file)}: pinned run-id "${m[0]}" — use stats.meta.model_run_id`)
      }
    }
    expect(offenders, `\n${offenders.join('\n')}\n`).toEqual([])
  })
})
