<script setup lang="ts">
import { ref, watch } from 'vue'
import { Menu, X } from 'lucide-vue-next'
import { RouterLink, RouterView, useRoute } from 'vue-router'
import { SITE } from '@/config/site'
import TaxYearBanner from '@/components/ui/TaxYearBanner.vue'
import stats from '@/data/siteStats.json'

const route = useRoute()
const mobileMenuOpen = ref(false)

watch(
  () => route.fullPath,
  () => {
    mobileMenuOpen.value = false
  },
)

/** Run provenance for the footer — regenerated by `fair-measure
 * export-web-stats`, so it tracks every model run automatically. The date is
 * day-only; format in UTC so it can't slip a day in western timezones. */
const runDate = new Date(`${stats.meta.generated_at}T00:00:00Z`).toLocaleDateString('en-US', {
  year: 'numeric',
  month: 'long',
  day: 'numeric',
  timeZone: 'UTC',
})
</script>

<template>
  <a class="skip-link" href="#main">Skip to main content</a>

  <!-- flag-gold rule: the one place gold touches the chrome -->
  <div class="h-1 bg-gold" aria-hidden="true"></div>

  <TaxYearBanner />

  <header class="border-b border-line bg-white">
    <nav
      class="mx-auto flex max-w-5xl items-center justify-between gap-1.5 px-4 py-3 sm:gap-4"
      aria-label="Main"
    >
      <RouterLink to="/" class="flex items-center gap-1.5 min-[480px]:gap-2.5" aria-label="Fair Measure home">
        <svg width="26" height="17" viewBox="0 0 26 17" aria-hidden="true" class="shrink-0">
          <rect x="1" y="6" width="24" height="7" rx="3.5" fill="#b9d2ee" />
          <rect x="11" y="2" width="3.5" height="15" rx="1.2" fill="#0f4d90" />
          <circle cx="21" cy="3" r="2.6" fill="#f3c613" />
        </svg>
        <span class="flex flex-col leading-none">
          <span class="text-base font-extrabold tracking-tight text-ink">Fair Measure</span>
          <span class="mt-0.5 text-[9.5px] font-semibold uppercase tracking-[0.09em] text-muted">Philadelphia</span>
        </span>
        <!-- Quiet beta chip stays off the narrowest phones. The footer explains
             what beta means; remove this when the model settles. -->
        <span
          aria-hidden="true"
          class="hidden shrink-0 rounded-full bg-brand-50 px-1 py-0.5 text-[10px] font-bold uppercase tracking-[0.08em] text-brand-600 min-[480px]:inline-block min-[480px]:px-1.5"
          >Beta</span
        >
      </RouterLink>
      <div class="flex items-center gap-2 text-body-sm font-semibold">
        <div class="hidden items-center gap-1.5 md:flex">
          <RouterLink
            to="/map"
            class="rounded-sm px-3 py-2 text-[#334155] hover:bg-brand-50"
            active-class="bg-brand-50 text-brand-600"
            >Map</RouterLink
          >
          <RouterLink
            to="/reports/ty-2027"
            class="rounded-sm px-3 py-2 text-[#334155] hover:bg-brand-50"
            active-class="bg-brand-50 text-brand-600"
            >2027 Report</RouterLink
          >
          <RouterLink
            to="/findings"
            class="rounded-sm px-3 py-2 text-[#334155] hover:bg-brand-50"
            active-class="bg-brand-50 text-brand-600"
            >Findings</RouterLink
          >
          <RouterLink
            to="/methodology"
            class="rounded-sm px-3 py-2 text-[#334155] hover:bg-brand-50"
            active-class="bg-brand-50 text-brand-600"
            >Methods</RouterLink
          >
          <RouterLink
            to="/trust"
            class="hidden rounded-sm px-3 py-2 text-[#334155] hover:bg-brand-50 lg:inline-flex"
            active-class="bg-brand-50 text-brand-600"
            >The Proof</RouterLink
          >
        </div>

        <div class="relative md:hidden" @keydown.esc="mobileMenuOpen = false">
          <button
            type="button"
            class="inline-flex h-9 w-9 items-center justify-center rounded-md border border-line text-body hover:bg-brand-50"
            :class="mobileMenuOpen ? 'bg-brand-50 text-brand-600' : ''"
            :aria-expanded="mobileMenuOpen"
            aria-controls="mobile-main-menu"
            @click="mobileMenuOpen = !mobileMenuOpen"
          >
            <X v-if="mobileMenuOpen" :size="19" aria-hidden="true" />
            <Menu v-else :size="20" aria-hidden="true" />
            <span class="sr-only">{{ mobileMenuOpen ? 'Close menu' : 'Open menu' }}</span>
          </button>

          <div
            v-if="mobileMenuOpen"
            id="mobile-main-menu"
            class="absolute right-0 top-full z-50 mt-2 w-48 overflow-hidden rounded-lg border border-line bg-white py-1 shadow-popover"
          >
            <RouterLink
              to="/map"
              class="block px-3 py-2.5 text-[#334155] hover:bg-brand-50"
              active-class="bg-brand-50 text-brand-600"
              @click="mobileMenuOpen = false"
              >Map</RouterLink
            >
            <RouterLink
              to="/reports/ty-2027"
              class="block px-3 py-2.5 text-[#334155] hover:bg-brand-50"
              active-class="bg-brand-50 text-brand-600"
              @click="mobileMenuOpen = false"
              >2027 assessment report</RouterLink
            >
            <RouterLink
              to="/findings"
              class="block px-3 py-2.5 text-[#334155] hover:bg-brand-50"
              active-class="bg-brand-50 text-brand-600"
              @click="mobileMenuOpen = false"
              >What we found</RouterLink
            >
            <RouterLink
              to="/methodology"
              class="block px-3 py-2.5 text-[#334155] hover:bg-brand-50"
              active-class="bg-brand-50 text-brand-600"
              @click="mobileMenuOpen = false"
              >How it works</RouterLink
            >
            <RouterLink
              to="/trust"
              class="block px-3 py-2.5 text-[#334155] hover:bg-brand-50"
              active-class="bg-brand-50 text-brand-600"
              @click="mobileMenuOpen = false"
              >Why trust these numbers</RouterLink
            >
          </div>
        </div>

        <RouterLink
          to="/appeal"
          class="rounded-md bg-brand-600 px-3 py-2 text-white hover:bg-brand-900"
          active-class="bg-brand-900"
          >Appeal</RouterLink
        >
      </div>
    </nav>
  </header>

  <main id="main" class="min-h-[70vh]">
    <RouterView />
  </main>

  <footer class="mt-12 border-t border-line bg-white">
    <div class="mx-auto max-w-5xl px-4 py-7">
      <!-- about: one paragraph, not five stacked lines; the whole footer is a
           centered colophon (glyph, paragraph, links, fine print) -->
      <div class="flex flex-col items-center text-center">
        <svg width="22" height="14" viewBox="0 0 26 17" aria-hidden="true" class="shrink-0">
          <rect x="1" y="6" width="24" height="7" rx="3.5" fill="#b9d2ee" />
          <rect x="11" y="2" width="3.5" height="15" rx="1.2" fill="#0f4d90" />
          <circle cx="21" cy="3" r="2.6" fill="#f3c613" />
        </svg>
        <p class="mt-2 max-w-3xl text-body-sm leading-relaxed text-muted">
          <strong class="text-ink">Fair Measure</strong> is a free, independent tool built only
          from the City of Philadelphia’s own open data. It is not run by the city. Our estimates
          are not appraisals, and nothing here is legal or tax advice. Before you act, check the
          city’s records at
          <a
            href="https://property.phila.gov"
            class="font-semibold text-brand-600 underline"
            rel="noopener"
            >property.phila.gov</a
          >.
        </p>
      </div>

      <!-- link row -->
      <nav
        aria-label="Footer"
        class="mt-4 flex flex-wrap justify-center gap-x-5 gap-y-2 text-body-sm font-semibold"
      >
        <RouterLink to="/reports/ty-2027" class="text-brand-600 underline">2027 assessment report</RouterLink>
        <RouterLink to="/findings" class="text-brand-600 underline">What we found</RouterLink>
        <RouterLink to="/methodology" class="text-brand-600 underline">How it works</RouterLink>
        <RouterLink to="/trust" class="text-brand-600 underline">Why trust these numbers</RouterLink>
        <a :href="SITE.githubUrl" rel="noopener" class="text-brand-600 underline">Code &amp; data pipeline</a>
        <a :href="SITE.modelDocsUrl" rel="noopener" class="text-brand-600 underline">Model documentation</a>
      </nav>

      <!-- beta + run provenance: one factual line, updated by every export -->
      <p class="mt-4 text-center text-caption text-muted">
        Fair Measure is in beta. Estimates come from the {{ runDate }} model run and can shift
        as the model improves. Spot a problem?
        <a :href="`${SITE.githubUrl}/issues`" rel="noopener" class="font-semibold text-brand-600 underline"
          >Open an issue</a
        >.
      </p>

      <!-- fine print -->
      <p class="mt-4 border-t border-line-faint pt-3 text-center text-caption text-faint">
        Designed and built by
        <a :href="SITE.creatorUrl" rel="noopener" class="font-semibold text-brand-600 underline"
          >{{ SITE.creatorName }}</a
        >
        · No ads, no cookies, anonymous usage statistics only · Independent, not a City of
        Philadelphia product
      </p>
    </div>
  </footer>
</template>
